### ISSUE TITLE
VeraCrypt EFI Bootloader does not reset watchdog

### ISSUE THREAD

**Issue by manison** [veracrypt/VeraCrypt-DCS#11]
Bootloader does not reset watchdog and if the password is not entered within 5 minutes then the entire  system is reset.

**Comment by idrassi** [comment]
Indeed, we reset the watchdog only for the Rescue Disk bootloader (DcsRe.c) and not the main bootloader (DcsBoot.c).
I will push a fix for this.

By the way, it is planned to add password timeout in the next version that will shutdown the machine after a certain time without entering the password (timeout action will be configurable).

Thank you for reporting this.

**Comment by idrassi** [comment]
Issue fixed in commit https://github.com/veracrypt/VeraCrypt-DCS/commit/c2582cc9a199b606835e8cdbf37991778efede4a
