### ISSUE TITLE
Error compiling DcsCfgCrypt.c with VS2017

### ISSUE THREAD

**Issue by manison** [veracrypt/VeraCrypt-DCS#16]
When I'm building DcsCfg under VS2017 (#13), I get the following error in _DcsCfgCrypt.c_:

> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(1766): error C2220: warning treated as error - no 'object' file generated
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(1766): warning C4459: declaration of 'SecRegionData' hides global declaration
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(49): note: see declaration of 'SecRegionData'
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(1767): warning C4459: declaration of 'SecRegionSize' hides global declaration
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(50): note: see declaration of 'SecRegionSize'
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(1768): warning C4459: declaration of 'SecRegionOffset' hides global declaration
> d:\shared\edk2\DcsPkg\DcsCfg\DcsCfgCrypt.c(51): note: see declaration of 'SecRegionOffset'

The local variables declared in `SecRigionDump` _(sic)_ or the warning should be suppressed.

There is also typo in `SecRigionXxx` functions. Apparently they should be named `SecRegionXxx`.

**Comment by idrassi** [comment]
Thank you for this report.
I have pushed 2 commits that fox this: one that renames the local variables in SecRigionDump (https://github.com/veracrypt/VeraCrypt-DCS/commit/59f630cfbbdb74b4b10756e86736b0b6e7c4cefd) and one that renames the functions SecRigionXxx to SecRegionXxx.
