### ISSUE TITLE
void HaltPrint(const CHAR16* Msg) should also clear the bootParams

### ISSUE THREAD

**Issue by DavidXanatos** [veracrypt/VeraCrypt-DCS#21]
void HaltPrint(const CHAR16* Msg) 
its triggered when something goes terribly wrong with the disk hook,
so its the last thing happens and it triggers CleanSensitiveData() so far so good, but what with the bootParams they contain sensitive data to and are not being cleared.
so the call should also MEM_BURNthe bootParams variable.

**Comment by idrassi** [comment]
@DavidXanatos The bootParams variable should indeed be clear like the others. I will push a fix for it.
